apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-container
        image: my-docker-hub/web-app:v1  # Replace with your app image
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DATABASE_URL
